### ISSUE TITLE
Install error: info file does not define a 'type' attribute

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/geofield#19]
The info file (temporary://update-extraction-892951e9/geofield-1.x-1.x/tests/geofield_openlayers_test.info) does not define a 'type' attribute.

**Comment by klonos** [comment]
As also mentioned on Gitter @deaddred I have just merged a change that should fix this problem. Long-term perhaps we should look into addressing this in core: https://github.com/backdrop/backdrop-issues/issues/1294

**Comment by klonos** [comment]
...I will go ahead and close this issue.
