### ISSUE TITLE
ETA or roadmap for an official release?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/geofield#2]
Hello, and thanks for porting this module to Backdrop CMS :)  I'm going to be using it on two of my Backdrop sites in the near future, and would love for it to have a stable release. Do you have a roadmap for issues preventing a stable release? I'd love to help get it across the finish line :)

see also: 
* https://github.com/backdrop-contrib/geocoder/issues/5
* https://github.com/backdrop-contrib/geophp/issues/2

**Comment by earthday47** [comment]
hi @jenlampton! Looks like I'm still listed as maintainer, although I haven't been involved for quite some time... 
I can help review and merge PRs. If you think we should search for a new maintainer, I'm okay with that as well.

**Comment by jenlampton** [comment]
Since I'll be using these projects heavily for the next month or so I'll likely have a lot of feedback and improvements. I'd love your review and approval throughout that process :) If it becomes too much of a burden I'm happy to be a co-maintainer for the time being, but I'd prefer to have you involved if you're willing :)

**Comment by earthday47** [comment]
Absolutely, I'm happy to help. Spinning up the latest Backdrop core now...

**Comment by quinnanya** [comment]
Hi all, any news on an official release for this? Geofield is a much better fit than Addressfield for the kinds of geographic data in the projects I work with, and it's the approach I used in "Drupal for Humanists". I'm not really a coder, but I'm happy to help test, write documentation, give feedback, etc. if it'd help.

**Comment by jenlampton** [comment]
I've been using the latest -dev of this project on several (live) sites, and so far it's been working great. I think it's ready for a 1.0.0 release. If there are any issues we can always follow up with a 1.0.1 etc, as needed. @earthday47 are you interested in creating an official release?

See also: https://github.com/backdrop-contrib/geofield/issues/17

**Comment by earthday47** [comment]
@jenlampton sure, sounds good! I'll have to educate myself a little bit all the steps needed to make one.

**Comment by stpaultim** [comment]
It would be great to get this released. Can I help in any way?

There is some information on creating a release here: 
https://github.com/backdrop-ops/contrib#what-to-do-after-your-application-is-accepted
https://github.com/backdrop-ops/contrib#releases

**Comment by earthday47** [comment]
Thanks @stpaultim for volunteering to help! Boy it's been a while...
I think where I last left off, I wanted to get https://github.com/backdrop-contrib/geofield/pull/20 merged first before I tagged a release. Perhaps you could run a fresh install with that branch and see if things looks gravy?

**Comment by earthday47** [comment]
I merged both open PRs and created a v1.0.0. So we're rolling! I'm creating an issue for v1.1 if anyone has any suggestions for what they'd like to see: https://github.com/backdrop-contrib/geofield/issues/26
