### ISSUE TITLE
Geofield throws "undefined function geofield_property_info_callback" error

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/geofield#29]
I do not manage to get any Geo functions working in Backdrop for quite some time... It seems that Geofield might be part of the problem.

- Install Geofield
- (and disable other geo modules, Geocoder, Geolocation)
- Create a new content type calle TEST
- Add a Geofield
- Create new node
- Try to save, get error message "called to undefined function geofield_property_info_callback

**Comment by mazzech** [comment]
Version: 7.2.28 (PHP information)

**Comment by laryn** [comment]
This should still be fixed here, but FYI I've also filed a PR to make this not fatal due to Entity Plus:
https://github.com/backdrop-contrib/entity_plus/issues/37

**Comment by laryn** [comment]
If I move `geofield_data_property_info()` and `geofield_property_info_callback()` into `geofield.module` instead of `geofield.schemaorg.inc` then this error disappears. Is that the right solution or the right place for these functions?

**Comment by djzwerg** [comment]
Same bug for me. How to solve? I'm not able to create a leaflet map with Geofield as data source because of this issue.

**Comment by laryn** [comment]
@djzwerg Are you able to test my suggestion https://github.com/backdrop-contrib/geofield/issues/29#issuecomment-680835595 ?

**Comment by djzwerg** [comment]
@laryn I'm sorry I don't know how to do that.

**Comment by laryn** [comment]
I added a PR here: https://github.com/backdrop-contrib/geofield/pull/32

**Comment by djzwerg** [comment]
I can confirm that this PR solves this issue!
