### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by diannevolek** [backdrop-contrib/geofield#34]
I installed and enabled, but didn't configure. Perhaps I should have?  The site now has the following error with a white screen. 

`The configuration file "field.instance.node.distributors.field_geofiel" is not properly formatted JSON. Contents: <pre> </pre>`

Perhaps something went wrong during installation, I will restore and try again.

**Comment by jenlampton** [comment]
I've not had any issues with installs since this was reported. If there was an issue it may have been fixed in a more recent release. I'm going to close this issue but if you are still having trouble, please re-open it and we can take a closer look.
