### ISSUE TITLE
Make geofield Rules-ready

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/geofield#35]
Currently, geofield properties such as longitud etc, can't be set or read by Rules. Doing so throws errors such as `Error: Call to undefined function entity_metadata_field_verbatim_get()`

Rules uses Entity Plus to get and set fields. In order to do that, contrib modules must define callbacks for their fields and properties. Geofield uses faulty callbacks that are not available in Entity Plus. Rather, those were available in Entity Metadata Wrapper, an old module that has been deprecated.

The faulty callbacks are:

- `entity_property_verbatim_get`
- `entity_property_verbatim_set`
- `entity_metadata_field_verbatim_get`
- `entity_metadata_field_verbatim_set`

All that's needed is to insert `_plus_` after `entity`

**Comment by jenlampton** [comment]
Does that mean that the current callbacks don't do anything at all? These are just left over from Drupal 7 entity API support? If so then I would commit a PR changing all the names :)

**Comment by argiepiano** [comment]
> Does that mean that the current callbacks don't do anything at all? These are just left over from Drupal 7 entity API support? If so then I would commit a PR changing all the names :)

Yup. That's all that's needed! Changing the names. The callbacks are strings that define what function must be called. Right now they point at inexistent functions.

**Comment by argiepiano** [comment]
@jenlampton here's a PR that fixes the callback names. #43

**Comment by herbdool** [comment]
Thanks @argiepiano. Merged.
