### ISSUE TITLE
Views proximity filter and field: replace #dependency with #states

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/geofield#36]
I'm going to add more detail soon, but for now I'd like to just not that the views filter and field are not working. The states seem to be broken at the least.

Update: I'm pretty sure it's because `#dependency` no longer does anything in  Views under Backdrop. I believe elsewhere in core Views they were replaced with `#states` so we should do that here too. Funnily `geofield_proximity_manual` already uses `#states` so can just use that example for all the other plugins.

**Comment by herbdool** [comment]
Here's the issue where this happened: https://github.com/backdrop/backdrop-issues/issues/40

**Comment by herbdool** [comment]
@jenlampton @earthday47 I've got a simple PR to fix the UI for proximity field/filter in Views. https://github.com/backdrop-contrib/geofield/pull/38

**Comment by herbdool** [comment]
@jenlampton reminder about this easy fix in my PR

**Comment by argiepiano** [comment]
@herbdool I've tested and LGMT!
