### ISSUE TITLE
Fatal error: cannot redeclare class geoPHP. geofield bundles geoPHP but geocoder requires installing geoPHP separately

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/geofield#37]
geofield and geocoder are both needed in a lot of setups. I can't think of why someone would use one without the other. But now that the geoPHP got bundled into this module in https://github.com/backdrop-contrib/geofield/issues/11, this creates a conflict with geocoder which requires installing geoPHP module, which also bundles the library. Thus fatal errors. 

Maybe this doesn't happen all the time, but it will when trying to use the proximity fields.

**Comment by herbdool** [comment]
@jenlampton I now see that https://github.com/backdrop-contrib/geocoder removed the dependency to geoPHP and added one for this module. But the latest release doesn't include that change. Please create a release there.

**Comment by jenlampton** [comment]
there is a new release for geocoder, so this should no longer be an issue.
