### ISSUE TITLE
Fix undefined function entity_metadata_field_verbatim_get and entity_metadata_field_verbatim_set

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/geofield#39]
> Error: Call to undefined function entity_metadata_field_verbatim_get() in EntityStructureWrapper->getPropertyValue() (line 453 of /app/httpdocs/modules/contrib/entity_plus/includes/entity_plus.wrapper.inc).

In geofield.module line 659, the callbacks should be: `entity_plus_metadata_field_verbatim_get` and `entity_plus_metadata_field_verbatim_set`

**Comment by herbdool** [comment]
@jenlampton I've got a PR. Quick fix.

**Comment by argiepiano** [comment]
@herbdool  LGTM! This fix resembles similar ones in several other contrib modules that used Entity API in D7.

**Comment by herbdool** [comment]
On behalf of the Bug Squad I created a new bug fix release for this and the other bug fix.
