### ISSUE TITLE
Get rid of dependency on Drupal compatibility layer

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/geofield#45]
There are loads of drupal_render() drupal_get_path(), drupal_add_js()... all over the place.

Are there any plans to clean that up?

Otherwise this module would break the site, if the setting `backdrop_drupal_compatibility` is off.

**Comment by herbdool** [comment]
@indigoxela if someone creates a PR then the @backdrop-contrib/bug-squad can RTBC and make a bug fix release.

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop-contrib/geofield/pull/46) is available now.

**Comment by herbdool** [comment]
I've reviewed the PR. All the backdrop replacements exist and work the same as the drupal ones, so I think this is RTBC. Thanks @indigoxela. @jenlampton this PR looks ready.

**Comment by argiepiano** [comment]
Merging on behalf of the @backdrop-contrib/bug-squad
