### ISSUE TITLE
Drupal compatibility layer still required for JS

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/geofield#52]
Follow-up to #46, where all the drupal_... have been fixed for PHP.

But the same problem still exists for JavaScript.

- js/viewsProximityValue.js
- js/geolocation.js

Both use `Drupal.behaviors`, but should use `Backdrop.behaviors` instead.

To reproduce, set `$settings['backdrop_drupal_compatibility'] = FALSE;`. The site won't break (as with PHP), but things like the proximity filter won't work, and there are errors in console logs.
```
Uncaught ReferenceError: Drupal is not defined
```

**Comment by indigoxela** [comment]
Here's a PR: https://github.com/backdrop-contrib/geofield/pull/53

@jenlampton or @earthday47 to your friendly consideration.
I'll come back to ping the bug squad, in case there wasn't any reply in a few weeks. :wink:

**Comment by indigoxela** [comment]
After two weeks without response, it's time to ping the @backdrop-contrib/bug-squad to come to the rescue with this obvious bug and trivial fix. :wink:

**Comment by argiepiano** [comment]
@indigoxela I've merged the fix. According to the [rules](https://backdropcms.org/leadership/bug-squad), I'm not sure if I can do a new release of this - is this a severe enough bug? Plus, @jenlampton is an active member of this community, so I trust she'll be able to do a new release soon.

**Comment by indigoxela** [comment]
> I'm not sure if I can do a new release of this - is this a severe enough bug?

TBH, I don't actually think so. Unlike the previous one (php), this one won't completely break the site, it "only" breaks functionality.

I'm aware that the situation with this module's a bit tricky. Although there are two maintainers listed, of which one is in theory active in the contrib community, pull requests are usually disregarded.

And the technical dept aggregates over time, unfortunately.

I could apply as (co-)maintainer, but I already maintain quite a number of modules, and this one just needs so much work. And it contains functionality, that contradicts my personal "OpenSource first" philosophy (Google stuff).

I only come back here occasionally, because one of the modules I maintain depends on geofield. :grimacing: 

Anyway, many thanks for merging, @argiepiano :pray:

**Comment by argiepiano** [comment]
I get that @indigoxela, but I've been in hot water before for making a release as a bug-squad member for a module that had a maintainer listed, and for which the bug was not considered fatal. I would appreciate other @backdrop-contrib/bug-squad member's thoughts.
